#!/usr/bin/env zsh


function rename() {
  for f in *.mp4; do
    twitch-renamer $f
  done
}

function convert() {
  for f in *.mp4; do
#    ab-av1 auto-encode --encoder libx265 --enc movflags=+faststart --input $f --output ../$f || exit 1
    ffmpeg -hide_banner -i $f -c:a copy -c:v libx265 -movflags +faststart ../$f || exit 1

    rm $f
  done
}


if [[ $1 = "rename" ]]; then
  rename
fi

if [[ $1 = "convert" ]]; then
  convert
fi

if [[ $1 = "all" ]]; then
  rename
  convert
fi
